"""Shared bounds for session checkpoint persistence and tool validation."""

SESSION_CHECKPOINT_SUMMARY_MAX = 360
SESSION_CHECKPOINT_GOAL_MAX = 240
SESSION_CHECKPOINT_NEXT_ACTION_MAX = 160
SESSION_CHECKPOINT_MAIN_ITEMS_MAX = 4
SESSION_CHECKPOINT_MAIN_ITEM_MAX = 160
SESSION_CHECKPOINT_MILESTONE_MAX = 220
SESSION_CHECKPOINT_TRAIL_MAX = 7
SESSION_CHECKPOINT_PROGRESS_LABEL_MAX = 160
SESSION_CHECKPOINT_ATTENTION_KEY_MAX = 120
SESSION_RESTART_CONTINUATION_MAX = 2_000
